/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClothingType = { 'accessory' : null } |
  { 'shirt' : null } |
  { 'jacket' : null } |
  { 'pants' : null } |
  { 'dress' : null };
export interface Submission {
  'creditsEarned' : bigint,
  'clothingType' : ClothingType,
  'timestamp' : Time,
  'quantity' : bigint,
  'submissionType' : SubmissionType,
}
export interface SubmissionResult {
  'status' : string,
  'creditsEarned' : bigint,
  'remainingBalance' : bigint,
}
export type SubmissionType = { 'resale' : null } |
  { 'upcycle' : null } |
  { 'recycle' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getGreenCreditBalance' : ActorMethod<[], bigint>,
  'getSubmission' : ActorMethod<[bigint], [] | [Submission]>,
  'getSubmissionCount' : ActorMethod<[], bigint>,
  'submitClothing' : ActorMethod<
    [SubmissionType, ClothingType, bigint],
    SubmissionResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];