/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClothingType = IDL.Variant({
  'accessory' : IDL.Null,
  'shirt' : IDL.Null,
  'jacket' : IDL.Null,
  'pants' : IDL.Null,
  'dress' : IDL.Null,
});
export const Time = IDL.Int;
export const SubmissionType = IDL.Variant({
  'resale' : IDL.Null,
  'upcycle' : IDL.Null,
  'recycle' : IDL.Null,
});
export const Submission = IDL.Record({
  'creditsEarned' : IDL.Nat,
  'clothingType' : ClothingType,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'submissionType' : SubmissionType,
});
export const SubmissionResult = IDL.Record({
  'status' : IDL.Text,
  'creditsEarned' : IDL.Nat,
  'remainingBalance' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getGreenCreditBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getSubmission' : IDL.Func([IDL.Nat], [IDL.Opt(Submission)], ['query']),
  'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitClothing' : IDL.Func(
      [SubmissionType, ClothingType, IDL.Nat],
      [SubmissionResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClothingType = IDL.Variant({
    'accessory' : IDL.Null,
    'shirt' : IDL.Null,
    'jacket' : IDL.Null,
    'pants' : IDL.Null,
    'dress' : IDL.Null,
  });
  const Time = IDL.Int;
  const SubmissionType = IDL.Variant({
    'resale' : IDL.Null,
    'upcycle' : IDL.Null,
    'recycle' : IDL.Null,
  });
  const Submission = IDL.Record({
    'creditsEarned' : IDL.Nat,
    'clothingType' : ClothingType,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'submissionType' : SubmissionType,
  });
  const SubmissionResult = IDL.Record({
    'status' : IDL.Text,
    'creditsEarned' : IDL.Nat,
    'remainingBalance' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getGreenCreditBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getSubmission' : IDL.Func([IDL.Nat], [IDL.Opt(Submission)], ['query']),
    'getSubmissionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitClothing' : IDL.Func(
        [SubmissionType, ClothingType, IDL.Nat],
        [SubmissionResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };