/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SubmissionResult {
    status: string;
    creditsEarned: bigint;
    remainingBalance: bigint;
}
export type Time = bigint;
export interface Submission {
    creditsEarned: bigint;
    clothingType: ClothingType;
    timestamp: Time;
    quantity: bigint;
    submissionType: SubmissionType;
}
export enum ClothingType {
    accessory = "accessory",
    shirt = "shirt",
    jacket = "jacket",
    pants = "pants",
    dress = "dress"
}
export enum SubmissionType {
    resale = "resale",
    upcycle = "upcycle",
    recycle = "recycle"
}
export interface backendInterface {
    getAllSubmissions(): Promise<Array<Submission>>;
    getGreenCreditBalance(): Promise<bigint>;
    getSubmission(id: bigint): Promise<Submission | null>;
    getSubmissionCount(): Promise<bigint>;
    submitClothing(submissionType: SubmissionType, clothingType: ClothingType, quantity: bigint): Promise<SubmissionResult>;
}
import type { ClothingType as _ClothingType, Submission as _Submission, SubmissionType as _SubmissionType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllSubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGreenCreditBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGreenCreditBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGreenCreditBalance();
            return result;
        }
    }
    async getSubmission(arg0: bigint): Promise<Submission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionCount();
            return result;
        }
    }
    async submitClothing(arg0: SubmissionType, arg1: ClothingType, arg2: bigint): Promise<SubmissionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitClothing(to_candid_SubmissionType_n9(this._uploadFile, this._downloadFile, arg0), to_candid_ClothingType_n11(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitClothing(to_candid_SubmissionType_n9(this._uploadFile, this._downloadFile, arg0), to_candid_ClothingType_n11(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
}
function from_candid_ClothingType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClothingType): ClothingType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionType): SubmissionType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Submission]): Submission | null {
    return value.length === 0 ? null : from_candid_Submission_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creditsEarned: bigint;
    clothingType: _ClothingType;
    timestamp: _Time;
    quantity: bigint;
    submissionType: _SubmissionType;
}): {
    creditsEarned: bigint;
    clothingType: ClothingType;
    timestamp: Time;
    quantity: bigint;
    submissionType: SubmissionType;
} {
    return {
        creditsEarned: value.creditsEarned,
        clothingType: from_candid_ClothingType_n4(_uploadFile, _downloadFile, value.clothingType),
        timestamp: value.timestamp,
        quantity: value.quantity,
        submissionType: from_candid_SubmissionType_n6(_uploadFile, _downloadFile, value.submissionType)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accessory: null;
} | {
    shirt: null;
} | {
    jacket: null;
} | {
    pants: null;
} | {
    dress: null;
}): ClothingType {
    return "accessory" in value ? ClothingType.accessory : "shirt" in value ? ClothingType.shirt : "jacket" in value ? ClothingType.jacket : "pants" in value ? ClothingType.pants : "dress" in value ? ClothingType.dress : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resale: null;
} | {
    upcycle: null;
} | {
    recycle: null;
}): SubmissionType {
    return "resale" in value ? SubmissionType.resale : "upcycle" in value ? SubmissionType.upcycle : "recycle" in value ? SubmissionType.recycle : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Array<Submission> {
    return value.map((x)=>from_candid_Submission_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ClothingType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClothingType): _ClothingType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionType): _SubmissionType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionType): {
    resale: null;
} | {
    upcycle: null;
} | {
    recycle: null;
} {
    return value == SubmissionType.resale ? {
        resale: null
    } : value == SubmissionType.upcycle ? {
        upcycle: null
    } : value == SubmissionType.recycle ? {
        recycle: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClothingType): {
    accessory: null;
} | {
    shirt: null;
} | {
    jacket: null;
} | {
    pants: null;
} | {
    dress: null;
} {
    return value == ClothingType.accessory ? {
        accessory: null
    } : value == ClothingType.shirt ? {
        shirt: null
    } : value == ClothingType.jacket ? {
        jacket: null
    } : value == ClothingType.pants ? {
        pants: null
    } : value == ClothingType.dress ? {
        dress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
